language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: sharedyourideasant-nodejs
  api_key:
    secure: EdlbAaX16+qriepWAodqxGHjL22q7Be1PclfvEYWLjRAYu335a37jyS4wZqcNeHLQ2z6bJNd/ngEQW8JAEE4AOa1rnZYkUYm+7Th9FSm7s38yt8IvLZ4CGe9gGFsmWUT657xA5rXP3f+vQURNGHx1LupF9ec14uK3+5e711pFmh67mYdvGDk6F99xL0po04rgD2HAgNKVnO4FTum0AMSiJqgV625afH5JBwy4bEhXNcD6R5RXyKS5Dk7cVw+JrGWL4Wgmp5xF1+iupNNXJSDmgeZ6MUG76NTeL2GvqMmqJ0uI11UiKkXBjUSB15YU2VLhhXZCd2JaTVDokhfu8f2eSmiLnQBcdKi4DZueIpkyzqHkgtdZLB2GBBraVrkYylt3zxuabz+ALEG0gStEVde4mkT/Mn9oXNFwR5lbA0d5UQnc2IDLEglMrUhusVjxvjMN6XDQzUP5mNrU3HhY3iESASl/MVbx5nurbSlXs8Z7xRAP04AhLf06dBJ6FB8iBCHaoLlAbSjE54yBOgImfx0j6ntwwldovaZg7sAQjg+GpgHJz6QGZO8HyY4pjrsn24cnPl4T3fbzvJ7xvLXbawQsvvgrW7De8N1pMgQEpyBJtpDB8z+89RhiO1kk2vEyZuQbAk8lgvrQA9BJJvxnrMHMEvThLNTANrO1xjPu+1oIZo=
